EventStack_MVC/Controllers/ListController.cs
using System.Reflection.Metadata;
using System;
using System.Net;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EventStack_MVC.Models;
using System.Threading.Tasks;
using System.Net.Http;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace EventStack_MVC.Controllers
{
    public class ListController : Controller
    {
        private HttpClient client;

        public ListController()
        {
            client = new HttpClient();
            System.Net.ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12 | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls;
        }

        public async Task<IActionResult> Index()
        {
            var eventList = new List<Event>();

            var url = @"http://localhost:44382/api/Event/GetAll";
            var httpRensponse = await client.GetAsync(url);

            if (httpRensponse.IsSuccessStatusCode)
                eventList = JsonConvert.DeserializeObject<List<Event>>(await httpRensponse.Content.ReadAsStringAsync());

            return View(eventList);
        }

        public IActionResult GetPhoto(byte[] photo)
        {;
            if (photo == null) Error();
            return File(photo, "image/png");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EventStack_MVC/Controllers/LoginController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EventStack_MVC.Models;
using System.Threading.Tasks;
using System.Net.Http;
using System.Collections.Generic;
using Newtonsoft.Json;
using System.Linq;

namespace EventStack_MVC.Controllers
{
    public class LoginController : Controller
    {
        private HttpClient client;

        public LoginController()
        {
            client = new HttpClient();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index([FromQuery]string email, [FromQuery]string password)
        {
            var organizationList = new List<Organization>();
            var url = @"https://localhost:44382/api/Organization";
            var httpRensponse = await client.GetAsync(url);

            if (httpRensponse.IsSuccessStatusCode)
                organizationList = JsonConvert.DeserializeObject<List<Organization>>(await httpRensponse.Content.ReadAsStringAsync());
            else
                return Error();

            var authenticatedUser = organizationList.FirstOrDefault(user => user.Email == email && user.Password == password);

            if(authenticatedUser != null)
            {
                // To do AuthenticationToken
            }

            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EventStack_MVC/Controllers/RegisterController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EventStack_MVC.Models;
using System.Threading.Tasks;

namespace EventStack_MVC.Controllers
{
    public class RegisterController : Controller
    {
        private readonly ILogger<RegisterController> _logger;

        public RegisterController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }
        public Task<IActionResult> CreateAccount([FromQuery]string email, [FromQuery]string password)
        {
            return null;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EventStack_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EventStack</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg  navbar-toggleable-lg navbar-light bg-white border-bottom box-shadow">
            <div class="container">
                <a asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/img/EventStack_NavBar_logo.png" width="80" height="80" class="navbar-brand"></a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse navbar-light">
                    <ul class="navbar-nav  flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="List" asp-action="Index">Lista Wydarzeń</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Login" asp-action="Index">Logowanie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Register" asp-action="Index">Rejestracja</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-black-50" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                            </div>
                            <form class="form-inline">
                        <input class="form-control mr-1 " type="search" placeholder="Wpisz nazwę eventu.." aria-label="Wyszukaj">
                        <button class="btn btn-dark" type="submit" >Szukaj</button>
                    
                            </form> 
                    </ul>
                   
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - EventStack - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>